### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ahaniart** [Timus-sumit/Neuro-fuzzy-hybrid-model-for-diabetes-prediction#1]
Dear Timus,
nice job 
please kindly tell me about the dataset. it is your kind if you can tell me where do you find it.

**Comment by Timus-sumit** [comment]
Thank You! I have used the Pima Indian Diabetes dataset, you can find that dataset here:-
https://www.kaggle.com/uciml/pima-indians-diabetes-database
